### ISSUE TITLE
Could you tell me if there are  public areas where can be seen by multi road cameras in rope3D datasets?

### ISSUE THREAD

**Issue by Egozjuer** [ADLab-AutoDrive/BEVHeight#10]
Hello,I want to search multi road camera perception likes nuscenes datasets,but i don't know if there are overlapping obstacles that can be seen by multi cameras,please tell me answer,than you!

**Comment by yanglei18** [comment]
At present, there is no open-sourced multi-view roadside dataset collected from real-world scenarios. The V2X-Sim is a simulation dataset in which RSU is equipped with four cameras.
