### ISSUE TITLE
代码环境报错

### ISSUE THREAD

**Issue by zhaoyanchen123** [ADLab-AutoDrive/BEVHeight#15]
感谢您的工作
![image](https://github.com/ADLab-AutoDrive/BEVHeight/assets/90304518/9d907805-5202-46a3-abfd-c6d0c73a2f20)
这里我拉取docker环境后，按照流程配置后，一直报错：找不到项目中定义的包。能给出一些建议吗

**Comment by yanglei18** [comment]
需要将BEVHeight代码路径加入Python环境变量，可在terminal中输入 export PYTHONPATH=./$PYTHONPATH

**Comment by zhaoyanchen123** [comment]
您好，能提供一下预训练权重嘛？我这边单张v100训了5000多轮为什么会自己停了？显卡也掉了



在 2023-05-10 16:44:08，"yanglei18" ***@***.***> 写道：

需要将BEVHeight代码路径加入Python环境变量，可在terminal中输入 export PYTHONPATH=./$PYTHONPATH
