### ISSUE TITLE
Quesion about y_{ref}^{virt}

### ISSUE THREAD

**Issue by LuPaoPao** [ADLab-AutoDrive/BEVHeight#17]
Thank you for your new perspective for BEV:
1. I'm a little confused about your formula 7. The meaning of  y_{ref}^{virt} is not given.
2. Can I give you the value of this matrix-the transformation matrix T_{cam}_^{virt}？
3. I'm not sure about the difference between y_{ref}^{cam} and y_{ref}^{virt}, and I think y_{ref}^{cam} to be a pseudo-3D plane with 1 depth. 
This will help me understand the problem. Thank you very much for your help.

**Comment by yanglei18** [comment]
1. $P_{ref}^{virt.} = (x_{ref}^{virt.}, y_{ref}^{virt.}, z_{ref}^{virt.})$
2. $T_{cam}^{virt.}$ is the transformation matrix from the camera coordinate to the virtual coordinate system.
3. $y_{ref}^{virt}$ is from $P_{ref}^{virt.} = (x_{ref}^{virt.}, y_{ref}^{virt.}, z_{ref}^{virt.})$, and $y_{ref}^{cam}$ is from $P_{ref}^{cam} = (x_{ref}^{cam}, y_{ref}^{cam}, z_{ref}^{cam})$

**Comment by LuPaoPao** [comment]
Thanks very much for your reply. 

I think I understand your paper now. 
But I'm still not sure how is T_{ref}^{cam} and T_{virt}^{ego}  determined.
Are the two transformation matrices dynamic, or a definite number. Can you tell me the specific expression?

Thanks again for you help.

**Comment by LuPaoPao** [comment]
> 1. Prefvirt.=(xrefvirt.,yrefvirt.,zrefvirt.)
> 
>     2. Tcamvirt. is the transformation matrix from the camera coordinate to the virtual coordinate system.
> 
>     3. yrefvirt is from Prefvirt.=(xrefvirt.,yrefvirt.,zrefvirt.), and yrefcam is from Prefcam=(xrefcam,yrefcam,zrefcam)

Thanks very much for your reply.

I think I understand your paper now.
But I'm still not sure how is T_{ref}^{cam} and T_{virt}^{ego} determined.
Are the two transformation matrices dynamic, or a definite number. Can you tell me the specific expression?

Thanks again for you help.

**Comment by yanglei18** [comment]
@LuPaoPao Please refer to the `get_sensor2virtual` function in `dataset/nusc_mv_det_dataset.py`
https://github.com/ADLab-AutoDrive/BEVHeight/blob/fa3bf883b0a804c2d23941d26d14f573c849ca78/dataset/nusc_mv_det_dataset.py#LL66C5-L66C23
