### ISSUE TITLE
Question about virtuallidar coordinate

### ISSUE THREAD

**Issue by Egozjuer** [ADLab-AutoDrive/BEVHeight#18]
In the DAIR-V2X dataset of label, we know that the Z-axis plane of the virtual LiDAR coordinate system is not on the ground. However, when you calculate "denorm" in the "gen_info_dair.py" script, you assume that the Z-values of the points on the ground in the virtual LiDAR coordinate system are all 0. Why is this the case?

**Comment by Egozjuer** [comment]
@yanglei18 please help，thank you！

**Comment by Egozjuer** [comment]
another question is why hwl also changes when label changes from lidar coordinate to camera coordinate(kitti) ,for example,the same object, 
    "3d_dimensions": { "h": "1.478958",   "w": "1.878626",   "l": "4.250516" }, but in kitti format, is 0.640204 4.257662 1.777448?

**Comment by yanglei18** [comment]
We use the `get_denorm(rotation_matrix, translation)` function in `gen_info_dair.py` to calculate `denorm`. The  input parameters are obtained through `r_velo2cam, t_velo2cam = get_velo2cam(virtuallidar_to_camera_path)`. In this way, the output `denorm` is corresponding to the horizontal plane of the virtual LiDAR coordinate system.

**Comment by yanglei18** [comment]
@Egozjuer please refer [def get_annos(path)](https://github.com/ADLab-AutoDrive/BEVHeight/blob/fa3bf883b0a804c2d23941d26d14f573c849ca78/scripts/gen_info_dair.py#L44) for more details.

**Comment by Egozjuer** [comment]
@yanglei18 ok,and I want to get depth_gt of dair dataset  ,how to get it ?
