### ISSUE TITLE
Where is the visualization codes?

### ISSUE THREAD

**Issue by yt7589** [ADLab-AutoDrive/BEVHeight#20]
It is a great work. Roadside BEV is what we need right now. I want to display the results. But I could not find the visualization codes in this project。I want to view the inference results just like the graph in the paper. How to display the inference results?

**Comment by LetStarFly** [comment]
Do you solve this problem?  I have the same question, I don't know how to visualize the result.

**Comment by yanglei18** [comment]
please refer to `https://github.com/ADLab-AutoDrive/BEVHeight/blob/main/scripts/data_converter/visual_tools.py`
