### ISSUE TITLE
Have you attempt to use auxiliary loss about the height liking BevDepth, what about the results, no improvement?

### ISSUE THREAD

**Issue by mayechi** [ADLab-AutoDrive/BEVHeight#22]

**Comment by yanglei18** [comment]
Please refer to the supplementary materials of our CVPR paper.

**Comment by mayechi** [comment]
I can not find it, which chapter said the above in the materials of your paper?

**Comment by yanglei18** [comment]
please refer to `https://openaccess.thecvf.com/content/CVPR2023/supplemental/Yang_BEVHeight_A_Robust_CVPR_2023_supplemental.pdf`

**Comment by mayechi** [comment]
I saw it , thank you. But I saw AP with ped and cyc in the table 5 are much lower than in the table 1, why?

**Comment by mayechi** [comment]
I saw it , thank you. But I saw AP with ped and cyc in the table 5 are much lower than in the table 1 on the main paper, why? Some differences about metric over these tables?
