### ISSUE TITLE
The question of metric in the code

### ISSUE THREAD

**Issue by mayechi** [ADLab-AutoDrive/BEVHeight#23]
I saw the voxel range is [0, -51.2, -5, 102.4, 51.2, 3] in the config, but the GT for the val data have many labels over the range, e.g. some cars' X coordinate are over 102.4m. So have you filtered the GT over the range when you calculating the mAP?

**Comment by yanglei18** [comment]
During the evaluation, we primarily focus on the prediction & GT within [0, -51.2, -5, 135.0, 51.2, 3], please refer to the
