### ISSUE TITLE
train and evaluate on the nuscenes

### ISSUE THREAD

**Issue by Ignite616** [ADLab-AutoDrive/BEVHeight#24]
Very nice job! Table4 in your paper reports the results on the nuscenes validation set, and I also saw your submission on the nuscenes test.
Can you provide the code for training and evaluation using nuscenes, thank you very much!

**Comment by yanglei18** [comment]
We are in the process of developing BEVHeight++, a method that achieves better performance on the nuScenes dataset. The article and code will be released together at a future time.
