### ISSUE TITLE
地图分割请教

### ISSUE THREAD

**Issue by handsomeZhuang** [ADLab-AutoDrive/BEVHeight#27]
您好，请问可以用来车道线检测和地图分割吗？谢谢！

**Comment by yanglei18** [comment]
车道线与地图都是分布在地面上的元素，在高度方向上分布更加集中，这或许可以更能凸显出我们所提Height-based pipeline的优势，很值得进一步尝试！

**Comment by handsomeZhuang** [comment]
> 

相比高度变换明显的目标，高度更加集中的情况下，我们的Height-base pipeline会更有效？还是有所退化？

**Comment by tudoujunx** [comment]
车道线和路面高度是一致的，怎么可能用高度把车道线分出来呢

**Comment by handsomeZhuang** [comment]
> 的Height-base pipeline会更有效

可以输出BEV视角的目标检测结果吗？我看着论文只有在LiDAR空间中输出了BEV视角，是否可以将路侧图像转到BEV视角输出？

**Comment by handsomeZhuang** [comment]
> 车道线与地图都是分布在地面上的元素，在高度方向上分布更加集中，这或许可以更能凸显出我们所提Height-based pipeline的优势，很值得进一步尝试！

请问一下大佬，可以输出路侧视角转BEV视角+目标检测结果输出吗？
