### ISSUE TITLE
During the evaluation, we primarily focus on the prediction & GT within [0, -51.2, -10, 135.0, 51.2, 10], please refer to the latest code base.

### ISSUE THREAD

**Issue by mayechi** [ADLab-AutoDrive/BEVHeight#28]
During the evaluation, we primarily focus on the prediction & GT within [0, -51.2, -10, 135.0, 51.2, 10], please refer to the latest code base.

_Originally posted by @yanglei18 in https://github.com/ADLab-AutoDrive/BEVHeight/issues/23#issuecomment-1683424869_
            I am doubt about it where I saw the post_center_range=[0.0, -61.2, -10.0, 122.4, 61.2, 10.0] and point_cloud_range=[0, -51.2, -5, 102.4, 51.2, 3] in every config of dair-v2x, so why you used [0, -51.2, -10, 135.0, 51.2, 10] during the evaluation?

**Comment by yanglei18** [comment]
What do you think I should do?

**Comment by mayechi** [comment]
First choice, i think you should filter the GT with the point_cloud_range=[0, -51.2, -5, 102.4, 51.2, 3] liking nuscence metirc filtering the GT with point_cloud_range=[-54, -54, -5.0, 54, 54, 3.0].
Second choice, i think you should modify the point_cloud_range=[0, -51.2, -5, 102.4, 51.2, 3] to [0, -51.2, -10, 135.0, 51.2, 3].
Because if the obs are farther than 102.4m and closer than 135.0m, you threw them away directly now.
