### ISSUE TITLE
The questions about tables in your main paper.

### ISSUE THREAD

**Issue by mayechi** [ADLab-AutoDrive/BEVHeight#29]
I saw AP with ped and cyc in the table 5 are much lower than in the table 1 on the main paper, why? Some differences about metric over these tables?

**Comment by yanglei18** [comment]
In Table 1, we use `exps/dair-v2x/bev_height_lss_r50_864_1536_128x128.py`, while in Table 5, we utilize `exps/dair-v2x/bev_height_lss_r101_864_1536_256x256.py`
