### ISSUE TITLE
rope2kitti is not correct

### ISSUE THREAD

**Issue by happyday-lkj** [ADLab-AutoDrive/BEVHeight#3]
hello,
     I use the script "rope2kitti.py" to convert the source data to kitti format, but the result seems not correct.
![000020](https://user-images.githubusercontent.com/18274241/228744286-5fcdd72c-62b4-49c5-851e-4d91b6844bd3.png)

**Comment by destinyls** [comment]
We have uploaded the visual_tools script, which can be found at the following link: "https://github.com/ADLab-AutoDrive/BEVHeight/blob/main/scripts/data_converter/visual_tools.py". This script will be used to verify the functionality of the "rope2kitti.py".

**Comment by yanglei18** [comment]
We have uploaded the visual_tool, which can be found at the following link: "https://github.com/ADLab-AutoDrive/BEVHeight/blob/main/scripts/data_converter/visual_tools.py". This script will be used to verify the functionality of the "rope2kitti.py".

**Comment by wanghangege** [comment]
Hello, I have also encountered the same problem, and the heading is not accurately marked, and there is also a slight deviation in the coordinate box. I speculate that the correction parameters of the original data are not accurate. How did you handle this situation?
![000005](https://user-images.githubusercontent.com/51116270/230828550-bbde88ff-dda6-4abd-a14d-17b9b1b93786.jpg)

![003037](https://user-images.githubusercontent.com/51116270/230828575-0e969d5f-0864-49fc-93c0-875bdd34fa8f.jpg)
![009912](https://user-images.githubusercontent.com/51116270/230828635-40e6ec60-3ed5-449e-adf8-399456f5484f.jpg)

**Comment by happyday-lkj** [comment]
> Hello, I have also encountered the same problem, and the heading is not accurately marked, and there is also a slight deviation in the coordinate box. I speculate that the correction parameters of the original data are not accurate. How did you handle this situation? ![000005](https://user-images.githubusercontent.com/51116270/230828550-bbde88ff-dda6-4abd-a14d-17b9b1b93786.jpg)
> 
> ![003037](https://user-images.githubusercontent.com/51116270/230828575-0e969d5f-0864-49fc-93c0-875bdd34fa8f.jpg) ![009912](https://user-images.githubusercontent.com/51116270/230828635-40e6ec60-3ed5-449e-adf8-399456f5484f.jpg)

It seems that your result is better, In fact, I do not use this data.

**Comment by wanghangege** [comment]
which data you used, hello?

**Comment by yanglei18** [comment]
@wanghangege 
**1. The heading is completely accurate. Please use our tools for visualization ("https://github.com/ADLab-AutoDrive/BEVHeight/blob/main/scripts/data_converter/visual_tools.py")
**2. We utilize the official dataset from  "https://thudair.baai.ac.cn/rope".

**Comment by yanglei18** [comment]
@wanghangege @happyday-lkj 
We utilize the public Rope3D datasets from "https://thudair.baai.ac.cn/rope" and achieve the accuracy reported in BEVHeight paper.

**Comment by wanghangege** [comment]
> 
Thank you for your excellent work. I am very interested in your approach and have encountered some issues with the data conversion process while trying to replicate it.
Thank you again for responding to me. However, I must point out that I used your dair2kitti tool and visualization work to convert the dair-v2x-i dataset. I did not use the Rope3D dataset. Before this, I also used code from other GitHub repositories for the conversion, but as I showed above, there was no difference in the results. Therefore, I suspect that the calibration parameters may have a bias (although a large part of the annotations are accurate). In addition, regarding the heading angle, as shown in the figure I attached above, "X" should represent the heading, which should actually (all) rotate counterclockwise by 90°. I don't know if my explanation is clear, but I will try my best to express my problem. If you have time to reply, I would be grateful.
this similar problem: https://github.com/destinyls/DAIR-V2X/issues/1

**Comment by destinyls** [comment]
@wanghangege 
**1. "scripts/rope2kitti.py" and "scripts/visual_tools.py" work perfectly fine. 
**2. There is a problem with the conversion of the orientation in "scripts/dair2kitti.py", which has been recently fixed in the latest commit (2023.4.11). You should pull our latest codebase.
**3. The orientation problem in "scripts/dair2kitti.py" does not have any effect on the mAP evaluation.
Thanks for your interest in our work！

**Comment by yanglei18** [comment]
@wanghangege
**1. "scripts/rope2kitti.py" and "scripts/visual_tools.py" work perfectly fine.
**2. There is a problem with the conversion of the orientation in "scripts/dair2kitti.py", which has been recently fixed in the latest commit (2023.4.11). You should pull our latest codebase.
**3. The orientation problem in "scripts/dair2kitti.py" does not have any effect on the mAP evaluation.
Thanks for your interest in our work！
