### ISSUE TITLE
python版本要求？安装mmdet3d报错

### ISSUE THREAD

**Issue by xuefeng1130** [ADLab-AutoDrive/BEVHeight#32]

**Comment by xuefeng1130** [comment]
<img width="982" alt="image" src="https://github.com/ADLab-AutoDrive/BEVHeight/assets/113966288/5812c6c1-24f9-4ed6-bf00-1e09e142bceb">
这一步安装失败，单独安装提示需要python3.9

**Comment by xduxiaohai** [comment]
同问，想知道ython版本是多少

**Comment by xduxiaohai** [comment]
我试了一下Python 3.9，好像可以

**Comment by deyang2000** [comment]
我在3.8的环境可以训练，但是不能测试。
