### ISSUE TITLE
OSError: Could not load shared object file: libllvmlite.so解决失败

### ISSUE THREAD

**Issue by xuefeng1130** [ADLab-AutoDrive/BEVHeight#34]
报错
OSError: Could not load shared object file: libllvmlite.so
解决
pip install numba==0.49.1 --ignore-installed llvmlite
依旧报错
<img width="908" alt="image" src="https://github.com/ADLab-AutoDrive/BEVHeight/assets/113966288/1d21363d-fad4-49f7-89c6-9995afdafb5f">

**Comment by XJTU-Haolin** [comment]
same problem meet @xuefeng1130  could you give me any instruction？ my wechat: qianmaifubi

**Comment by xuefeng1130** [comment]
> same problem meet @xuefeng1130 could you give me any instruction？ my wechat: qianmaifubi

我忘记我是怎么解决这个问题的了，我之前还发布过几个issue，你可以看看有没有描述，因为我换过好几个服务器

**Comment by liuanqi-libra7** [comment]
@xuefeng1130 You can try this
`pip install --ignore-installed llvmlite==0.35.0`
and 
`pip install numba==0.48.0`
