### ISSUE TITLE
训练结果怎么查看？和论文中数据对比

### ISSUE THREAD

**Issue by xuefeng1130** [ADLab-AutoDrive/BEVHeight#35]
代码中计算指标或结果的公式在哪里？

**Comment by xuefeng1130** [comment]
图1如何对比？
<img width="707" alt="image" src="https://github.com/ADLab-AutoDrive/BEVHeight/assets/113966288/d55fc601-eeeb-4b11-9c58-afc9339a082e">
是用哪一个训练和推理？可视化结果怎么生成？

**Comment by xuefeng1130** [comment]
<img width="425" alt="image" src="https://github.com/ADLab-AutoDrive/BEVHeight/assets/113966288/d19cac8f-98e3-4818-b584-c8106dcbcc4f">
输出和论文中表格怎么对比？

**Comment by xduxiaohai** [comment]
可视化结果我是仿照scripts/dataconverter/visual_tools.py 重新写了代码。具体是读取outputs/data里面的标签，在data/dair-v2x-i/image的每一张图片上执行draw_3d_box_on_image(image, label, P2, denorm)这个函数，就可以得到推理的结果

**Comment by xuefeng1130** [comment]
> 可视化结果我是仿照scripts/dataconverter/visual_tools.py 重新写了代码。具体是读取outputs/data里面的检测结果，在data/dair-v2x-i/image的每一张图片上执行draw_3d_box_on_image(image, label, P2, denorm)这个函数，就可以得到推理的结果

可以分享一下吗

**Comment by xuefeng1130** [comment]
> 像这样的 ![image](https://user-images.githubusercontent.com/53559220/276237225-8b85db25-8785-4c51-b20f-e1e474537648.png) 另外我想请教一下你是怎么配置环境的。
> 
> 我输入python [EXP_PATH] --ckpt_path [CKPT_PATH] -e -b 8 --gpus 8在评估的时候报错了，提示 ![image](https://user-images.githubusercontent.com/53559220/276240829-dde004e3-78b6-4c4d-9ca7-1c8edbab1151.png)
> 
> 我的环境是 Ubuntu20.04+cuda11.1+pytorch1.9,部分pip配置如下： ![image](https://user-images.githubusercontent.com/53559220/276239836-54ac3c84-ad6e-4f1c-8a41-44e1e42c9898.png)
> 
> ![image](https://user-images.githubusercontent.com/53559220/276239837-e871ae67-6cfe-4039-a60d-9dfa6dae7a84.png)
> 
> ![image](https://user-images.githubusercontent.com/53559220/276240500-23247b0a-101a-47c8-a362-acdc0b9f254f.png)

好的，非常感谢，我去试试

**Comment by xuefeng1130** [comment]
> 像这样的 ![image](https://user-images.githubusercontent.com/53559220/276237225-8b85db25-8785-4c51-b20f-e1e474537648.png) 另外我想请教一下你是怎么配置环境的。
> 
> 我输入python [EXP_PATH] --ckpt_path [CKPT_PATH] -e -b 8 --gpus 8在评估的时候报错了，提示 ![image](https://user-images.githubusercontent.com/53559220/276240829-dde004e3-78b6-4c4d-9ca7-1c8edbab1151.png)
> 
> 我的环境是 Ubuntu20.04+cuda11.1+pytorch1.9,部分pip配置如下： ![image](https://user-images.githubusercontent.com/53559220/276239836-54ac3c84-ad6e-4f1c-8a41-44e1e42c9898.png)
> 
> ![image](https://user-images.githubusercontent.com/53559220/276239837-e871ae67-6cfe-4039-a60d-9dfa6dae7a84.png)
> 
> ![image](https://user-images.githubusercontent.com/53559220/276240500-23247b0a-101a-47c8-a362-acdc0b9f254f.png)

我是在远程服务器上配置的，这个问题这样解决：
报错
numba.cuda.cudadrv.error.NvvmError: Failed to compile

<unnamed> (66, 23): parse expected comma after load's type
NVVM_ERROR_COMPILATION
解决
conda install numba==0.53.0

**Comment by xduxiaohai** [comment]
我试了一下还是不行，这个numba和cuda加速的就没成功过，我想看下你上述的一些环境配置，可以吗？

**Comment by xuefeng1130** [comment]
> 我试了一下还是不行，这个numba和cuda加速的就没成功过，我想看下你上述的一些环境配置，可以吗？

可以
对了还有一步，不加速，以下是完整：
报错
numba.errors.TypingError: Failed in nopython mode pipeline (step: nopython mode backend)
解决
@numba.jit(nopython=True) 去掉nopython=True

报错
numba.cuda.cudadrv.error.NvvmError: Failed to compile

<unnamed> (66, 23): parse expected comma after load's type
NVVM_ERROR_COMPILATION
解决
conda install numba==0.53.0

报错
SystemError: initialization of _internal failed without raising an exception
解决
conda install numpy==1.23.4

**Comment by xuefeng1130** [comment]
> 我试了一下还是不行，这个numba和cuda加速的就没成功过，我想看下你上述的一些环境配置，可以吗？

> 可视化结果我是仿照scripts/dataconverter/visual_tools.py 重新写了代码。具体是读取outputs/data里面的检测结果，在data/dair-v2x-i/image的每一张图片上执行draw_3d_box_on_image(image, label, P2, denorm)这个函数，就可以得到推理的结果

鸟瞰图的结果能看到吗，这个是3D检测结果

**Comment by xduxiaohai** [comment]
鸟瞰图这部分我还没有尝试了

**Comment by xduxiaohai** [comment]
> > 我试了一下还是不行，这个numba和cuda加速的就没成功过，我想看下你上述的一些环境配置，可以吗？
> 
> 可以 对了还有一步，不加速，以下是完整： 报错 numba.errors.TypingError: Failed in nopython mode pipeline (step: nopython mode backend) 解决 @numba.jit(nopython=True) 去掉nopython=True
> 
> 报错 numba.cuda.cudadrv.error.NvvmError: Failed to compile
> 
> (66, 23): parse expected comma after load's type NVVM_ERROR_COMPILATION 解决 conda install numba==0.53.0
> 
> 报错 SystemError: initialization of _internal failed without raising an exception 解决 conda install numpy==1.23.4

感谢，现在可以评估了，但是评估结果没有看懂

**Comment by xuefeng1130** [comment]
> > > 我试了一下还是不行，这个numba和cuda加速的就没成功过，我想看下你上述的一些环境配置，可以吗？
> > 
> > 
> > 可以 对了还有一步，不加速，以下是完整： 报错 numba.errors.TypingError: Failed in nopython mode pipeline (step: nopython mode backend) 解决 @numba.jit(nopython=True) 去掉nopython=True
> > 报错 numba.cuda.cudadrv.error.NvvmError: Failed to compile
> > (66, 23): parse expected comma after load's type NVVM_ERROR_COMPILATION 解决 conda install numba==0.53.0
> > 报错 SystemError: initialization of _internal failed without raising an exception 解决 conda install numpy==1.23.4
> 
> 感谢，现在可以评估了，但是评估结果没有看懂

好的，我也正在看，

**Comment by xuefeng1130** [comment]
> 鸟瞰图这部分我还没有尝试了

源码中有吗？

**Comment by xduxiaohai** [comment]
> > 鸟瞰图这部分我还没有尝试了
> 
> 源码中有吗？

暂时没看到

**Comment by xduxiaohai** [comment]
我这边rtx3090 训练了53个epoch，评估结果是这样的，指标相对低一些，想问一下你那边训练是怎么设置的？训练了多少个epoch？
Car AP@0.70, 0.70, 0.70:
bbox AP:81.9206, 78.4629, 78.5262
bev  AP:58.6792, 53.2915, 53.3534
3d   AP:32.1143, 28.4033, 28.3941
aos  AP:81.73, 78.28, 78.27
Car AP@0.70, 0.50, 0.50:
bbox AP:81.9206, 78.4629, 78.5262
bev  AP:86.0225, 82.7895, 82.8373
3d   AP:78.1037, 74.5459, 74.6214
aos  AP:81.73, 78.28, 78.27
Pedestrian AP@0.50, 0.50, 0.50:
bbox AP:56.1036, 55.1801, 55.5653
bev  AP:4.2019, 4.0465, 4.0632
3d   AP:3.0422, 2.7500, 2.7546
aos  AP:49.57, 48.63, 48.96
Pedestrian AP@0.50, 0.25, 0.25:
bbox AP:56.1036, 55.1801, 55.5653
bev  AP:25.3276, 24.6396, 24.7127
3d   AP:23.7069, 22.4873, 22.5430
aos  AP:49.57, 48.63, 48.96
Cyclist AP@0.50, 0.50, 0.50:
bbox AP:77.5332, 79.1622, 79.4373
bev  AP:12.2328, 14.8138, 15.2712
3d   AP:8.1122, 10.3512, 10.7235
aos  AP:73.66, 75.60, 75.84
Cyclist AP@0.50, 0.25, 0.25:
bbox AP:77.5332, 79.1622, 79.4373
bev  AP:47.1900, 50.6809, 51.3687
3d   AP:44.0845, 47.4992, 48.1157
aos  AP:73.66, 75.60, 75.84

Overall AP@easy, moderate, hard:
bbox AP:71.8525, 70.9350, 71.1763
bev  AP:25.0379, 24.0506, 24.2292
3d   AP:14.4229, 13.8348, 13.9574
aos  AP:68.32, 67.50, 67.6

**Comment by xuefeng1130** [comment]
> 我这边rtx3090 训练了53个epoch，评估结果是这样的，指标相对低一些，想问一下你那边训练是怎么设置的？训练了多少个epoch？ Car AP@0.70, 0.70, 0.70: bbox AP:81.9206, 78.4629, 78.5262 bev AP:58.6792, 53.2915, 53.3534 3d AP:32.1143, 28.4033, 28.3941 aos AP:81.73, 78.28, 78.27 Car AP@0.70, 0.50, 0.50: bbox AP:81.9206, 78.4629, 78.5262 bev AP:86.0225, 82.7895, 82.8373 3d AP:78.1037, 74.5459, 74.6214 aos AP:81.73, 78.28, 78.27 Pedestrian AP@0.50, 0.50, 0.50: bbox AP:56.1036, 55.1801, 55.5653 bev AP:4.2019, 4.0465, 4.0632 3d AP:3.0422, 2.7500, 2.7546 aos AP:49.57, 48.63, 48.96 Pedestrian AP@0.50, 0.25, 0.25: bbox AP:56.1036, 55.1801, 55.5653 bev AP:25.3276, 24.6396, 24.7127 3d AP:23.7069, 22.4873, 22.5430 aos AP:49.57, 48.63, 48.96 Cyclist AP@0.50, 0.50, 0.50: bbox AP:77.5332, 79.1622, 79.4373 bev AP:12.2328, 14.8138, 15.2712 3d AP:8.1122, 10.3512, 10.7235 aos AP:73.66, 75.60, 75.84 Cyclist AP@0.50, 0.25, 0.25: bbox AP:77.5332, 79.1622, 79.4373 bev AP:47.1900, 50.6809, 51.3687 3d AP:44.0845, 47.4992, 48.1157 aos AP:73.66, 75.60, 75.84
> 
> Overall AP@easy, moderate, hard: bbox AP:71.8525, 70.9350, 71.1763 bev AP:25.0379, 24.0506, 24.2292 3d AP:14.4229, 13.8348, 13.9574 aos AP:68.32, 67.50, 67.6

我和源码要求一样，我看你的结果和论文中差的也不多
<img width="1303" alt="image" src="https://github.com/ADLab-AutoDrive/BEVHeight/assets/113966288/b6190c10-d057-4e13-acdc-35825b54d916">

**Comment by xuefeng1130** [comment]
> 不好意思，怎么看出来结果差不多的呀，还有就是我是跑的R50 128 x 128这一个配置的训练

<img width="813" alt="image" src="https://github.com/ADLab-AutoDrive/BEVHeight/assets/113966288/30370de1-b3bf-43ce-b11a-437e34e682c9">
<img width="818" alt="image" src="https://github.com/ADLab-AutoDrive/BEVHeight/assets/113966288/b4bd45f9-2917-407e-8ce5-0ba04c523f57">
