### ISSUE TITLE
Evaluation for the Rope3d

### ISSUE THREAD

**Issue by zhenjiaa** [ADLab-AutoDrive/BEVHeight#4]
Thank you for your excellent work, I have some questions for you. 
**1. Whether the evaluation of Rope3d is filtered according to the mask provided by the official?
**2. Can you provide the code of bevdepth and bevformer for the Rope3d?
Looking forward to your reply

**Comment by destinyls** [comment]
Thank you for your attention.
**1. Yes, please visit "https://github.com/liyingying0113/rope3d-dataset-tools/tree/main/eval_tools" for more details.
**2. We are working on a unified code base supporting bevformer, bevdepth baselines and other roadside datasets which will be open source.

**Comment by yanglei18** [comment]
Thank you for your attention.
**1. Yes, please visit "https://github.com/liyingying0113/rope3d-dataset-tools/tree/main/eval_tools" for more details.
**2. We are working on a unified code base supporting bevformer, bevdepth baselines and other roadside datasets which will be open source.
