### ISSUE TITLE
Question about "d_bound" in config file

### ISSUE THREAD

**Issue by XJTU-Haolin** [ADLab-AutoDrive/BEVHeight#40]
After comparing configs between DAIR and Rope3D, I found a big difference in "d_bound" of the Backbone config. 
I am not sure what is the exact meaning of "d_bound" (I guess the parameters are related to "height") and why different values are predefined for two datasets. How do we judge and define the values of "d_bound" for a new scene or custom dataset? depends on sensors, or camera pose? 

Thanks for your time!

**Comment by luqinwei** [comment]
I have the same question. Did you solve it?

**Comment by yanglei18** [comment]
@XJTU-Haolin `d_bound` indicates the height range of vehicles compared to a reference ground plane. In the BEVHeight codebase for the Rope3D dataset, the reference ground plane closely matches the real one. For the DAIR-V2X dataset, it's the horizontal plane of the Virtual LiDAR system, positioned higher than the actual ground.
