### ISSUE TITLE
custom dataset inference details 

### ISSUE THREAD

**Issue by Fengzexu** [ADLab-AutoDrive/BEVHeight#43]
Your work is very amazing. I now have a roadside video. I just want to use the pre-training model to reason and try the effect. What should I do? I only have RGB image data and no camera parameters. Can I infer images  without these parameters?

**Comment by yaobaishen** [comment]
I have the same request, is there a guideline available for how to use the pre-train model to try inference? Thanks.

**Comment by yanglei18** [comment]
@Fengzexu  For BEVHeight model, camera parameters are necessary during the 2D-3D projection.

**Comment by yanglei18** [comment]
@yaobaishen You can utilize the following script to make inferences with a pre-trained model. 
`[CKPT_PATH]` is the path for pre-trained model.
`python [EXP_PATH] --ckpt_path [CKPT_PATH] -e -b 8 --gpus 8`
