### ISSUE TITLE
About the Height-based 2D-3D projection module

### ISSUE THREAD

**Issue by pppp-k** [ADLab-AutoDrive/BEVHeight#48]
I can’t find **the Height-based 2D-3D projection module** in this project.
Could you tell me where can I find it or which  file is it in.
I'd really appreciate it if you could answer it
@yanglei18 
![862c339fe1bba79f850a3e74545f1bc](https://github.com/ADLab-AutoDrive/BEVHeight/assets/75902731/b9f2d998-cefa-41a4-af77-cfe4e0ffcc6e)

**Comment by weitunglin** [comment]
same question here, lots of issues about this paper, could someone explain?

**Comment by yanglei18** [comment]
@weitunglin @pppp-k  Please refer to the `height2localtion` function in `lss_fpn.py`
https://github.com/ADLab-AutoDrive/BEVHeight/blob/f5894ab98525a4cd3a93f86d401356c02863499e/layers/backbones/lss_fpn.py#L334C9-L334C25
