### ISSUE TITLE
gen_info_dair import error

### ISSUE THREAD

**Issue by fjzpcmj** [ADLab-AutoDrive/BEVHeight#5]
https://github.com/ADLab-AutoDrive/BEVHeight/blob/fa3bf883b0a804c2d23941d26d14f573c849ca78/scripts/gen_info_dair.py#L10
it seems this line should be commented？otherwise， there will be import error “ModuleNotFoundError: No module named 'scripts.vis_utils'”

**Comment by yanglei18** [comment]
You should "export PYTHONPATH=./$PYTHONPATH" in the terminal.

**Comment by fjzpcmj** [comment]
> You should "export PYTHONPATH=./$PYTHONPATH" in the terminal.

Thanks, is there any difference bettween with and without this line? It seems that without this line, the script also can be run.

**Comment by destinyls** [comment]
You can try "export PYTHONPATH=./$PYTHONPATH" if meet “ModuleNotFoundError: No module named 'scripts.vis_utils'”, otherwise is not necessary.

**Comment by yanglei18** [comment]
You can try "export PYTHONPATH=./$PYTHONPATH" if meet “ModuleNotFoundError: No module named 'scripts.vis_utils'”, otherwise is not necessary.
