### ISSUE TITLE
what devices and resources are required?

### ISSUE THREAD

**Issue by sunnyHelen** [ADLab-AutoDrive/BEVHeight#7]
Hi, thanks for sharing the great work. I want to know what devices and resources are needed to do this work. For example, the GPU card version, the memory size, and the training time for one experiment.

**Comment by yanglei18** [comment]
We train the model with a batch size of 16/8 on 8 NVIDIA GeForce RTX 3090 GPUs for BEVHeight-R50-128x128.  On the DAIR-V2X-I dataset, the reported performance is achieved in 80 epochs, taking 8 hours.

**Comment by yanglei18** [comment]
Yes, exactly！

**Comment by changjiahao** [comment]
> @sunnyHelen Yes, exactly！
HI,How to ensure that the height predictions of the same object at different distances are consistent?

**Comment by tdd233** [comment]
> We train the model with a batch size of 16/8 on 8 NVIDIA GeForce RTX 3090 GPUs for BEVHeight-R50-128x128. On the DAIR-V2X-I dataset, the reported performance is achieved in 80 epochs, taking 8 hours.

Hi, could you please tell me the version of python and cuda? I have tried many versions on GeForce RTX3090 following your installation tips, but there are still some problems, etc. 
![image](https://github.com/user-attachments/assets/473fb992-6ddb-4fd1-8d17-2926ab823f30)
