### ISSUE TITLE
calculation of yaw in result2kitti seems incorrect

### ISSUE THREAD

**Issue by chenxiahan** [ADLab-AutoDrive/BEVHeight#9]
https://github.com/ADLab-AutoDrive/BEVHeight/blob/fa3bf883b0a804c2d23941d26d14f573c849ca78/evaluators/result2kitti.py#L226

The calculation of yaw from yaw_lidar to yaw_cam seems not correct. And the heading testing results of DAIR  is not accurately marked if yaw=0.5 * np.pi - yaw_lidar.

Is it `yaw  = -0.5 * np.pi - yaw_lidar` ? (reference label_json2kitti.py#L23)

For example: 

`yaw  = 0.5 * np.pi - yaw_lidar` 
![000045](https://user-images.githubusercontent.com/52770249/233047528-c5a0939d-945b-451e-913f-31437e7532a8.jpg)

`yaw  = -0.5 * np.pi - yaw_lidar` 
![000045](https://user-images.githubusercontent.com/52770249/233047185-faae6fed-9c90-4c64-9d61-e042a398b48a.jpg)

**Comment by yanglei18** [comment]
@chenxiahan 
Yes, ```yaw  = -0.5 * np.pi - yaw_lidar``` is correct.

**Comment by chenxiahan** [comment]
Thanks for your reply and excellent work!

if `yaw  = -0.5 * np.pi - yaw_lidar` is correct,  the calcation of rotation in gen_info_rope3d.py is also incorrect as follows: 
https://github.com/ADLab-AutoDrive/BEVHeight/blob/fa3bf883b0a804c2d23941d26d14f573c849ca78/scripts/gen_info_rope3d.py#L104

Is it `rotation =  -0.5 * np.pi - ry`?
